packages:
  - "apps/next.js/*"
  - "apps/react/*"
  - "packages/*"

catalog:
  react: "19.1.0"
  react-dom: "19.1.0"
  lucide-react: "0.525.0"
  tailwindcss: "4.1.7"
  "@clerk/nextjs": "6.24.0"
  "@clerk/clerk-react": "5.32.3"
  eslint: "9.29.0"
  typescript: "5.8.3"
  "@types/react": "19.1.8"
  "@types/react-dom": "19.1.6"
  zod: "3.25.63"
  jiti: "2.4.2"
