packages:
  - apps/next.js/*
  - apps/react/*
  - packages/*

catalog:
  "@clerk/clerk-react": 5.51.0
  "@clerk/nextjs": 6.33.3
  "@types/react": 19.2.2
  "@types/react-dom": 19.2.1
  eslint: 9.37.0
  jiti: 2.6.1
  lucide-react: 0.548.0
  next: 15.5.4
  react: 19.2.0
  react-dom: 19.2.0
  tailwindcss: 4.1.14
  typescript: 5.9.3
  zod: 3.25.76
