packages:
  - apps/next.js/*
  - apps/react/*
  - packages/*

catalog:
  "@clerk/clerk-react": 5.32.3
  "@clerk/nextjs": 6.24.0
  "@types/react": 19.1.8
  "@types/react-dom": 19.1.6
  eslint: 9.32.0
  jiti: 2.4.2
  lucide-react: 0.534.0
  next: 15.3.3
  react: 19.1.0
  react-dom: 19.1.0
  tailwindcss: 4.1.7
  typescript: 5.8.3
  zod: 3.25.63
