packages:
  - apps/next.js/*
  - apps/react/*
  - packages/*

catalog:
  "@clerk/clerk-react": 5.59.2
  "@clerk/nextjs": 6.36.5
  "@clerk/testing": 1.13.26
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  eslint: 9.39.2
  jiti: 2.6.1
  lucide-react: 0.562.0
  next: 15.5.9
  react: 19.2.3
  react-dom: 19.2.3
  tailwindcss: 4.1.18
  typescript: 5.9.3
  zod: 3.25.76
