packages:
  - apps/next.js/*
  - apps/react/*
  - packages/*

catalog:
  "@clerk/react-router": 1.10.2
  "@clerk/nextjs": 6.32.0
  "@types/react": 19.1.13
  "@types/react-dom": 19.1.9
  eslint: 9.35.0
  jiti: 2.5.1
  lucide-react: 0.544.0
  next: 15.5.3
  react: 19.1.1
  react-dom: 19.1.1
  react-router: 7.9.2
  tailwindcss: 4.1.13
  typescript: 5.9.2
  zod: 3.25.76
