packages:
  - apps/next.js/*
  - apps/react/*
  - packages/*

catalog:
  "@clerk/clerk-react": 5.42.1
  "@clerk/nextjs": 6.31.1
  "@types/react": 19.1.10
  "@types/react-dom": 19.1.7
  eslint: 9.33.0
  jiti: 2.5.1
  lucide-react: 0.534.0
  next: 15.4.6
  react: 19.1.1
  react-dom: 19.1.1
  tailwindcss: 4.1.12
  typescript: 5.9.2
  zod: 3.25.76
