import type { Metadata } from 'next';
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from '@clerk/nextjs';
import Navbar from '@/components/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const primarySignInUrl = '/sign-in';
  // const primarySignUpUrl = '/sign-up';
  return (
    <ClerkProvider 
    // signInUrl={primarySignInUrl}
    // signUpUrl={primarySignUpUrl}
    allowedRedirectOrigins={['http://localhost:3001']}
    >
      <html lang='en'>
        <body>
         <Navbar/>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
