import type { Metadata } from 'next';
import { ClerkProvider,} from '@clerk/nextjs';
import Navbar from '@/components/Header';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const primarySignInUrl = 'http://localhost:3000/sign-in';
  // const primarySignUpUrl = 'http://localhost:3000/sign-up';
  // const domain = 'http://localhost:3000';

  return (
    <ClerkProvider
    // isSatellite
    // domain={domain}
    // signInUrl={primarySignInUrl}
    // signUpUrl={primarySignUpUrl}
    >
      <html lang='en'>
        <body>
          <Navbar/>
          <main>{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}
